### ISSUE TITLE
RuntimeError: Variable data has to be a tensor, but got int

### ISSUE THREAD

**Issue by SeekPoint** [berlino/MemNN#1]
mldl@mldlUB1604:~/ub16_prj/MemNN$ python train_mlp.py 
Loading:  train_pair.pkl
Loading:  dev_pair.pkl
5618800 batches expected
5618800 batches expected
5618800 batches expected
Traceback (most recent call last):
  File "train_mlp.py", line 47, in <module>
    train()
  File "train_mlp.py", line 39, in train
    loss = model.forward(i_q, i_a, i_s)
  File "/home/mldl/ub16_prj/MemNN/Model.py", line 24, in forward
    y = Variable(y)
RuntimeError: Variable data has to be a tensor, but got int
mldl@mldlUB1604:~/ub16_prj/MemNN$

**Comment by bethke** [comment]
I am having the same issue - this is when running train_mlp.py.  
Has anyone found a workaround or solution?

**Comment by berlino** [comment]
Sorry for the delay.

It's a bug in utils.py, I already fix it. You just need to check out this file and run train_mlp.py and you don't need to generate the data again.

This repo is a little bit undocumented. If you got any problems, feel free to let me know.
Thanks

**Comment by bethke** [comment]
Thanks so much!
